### ISSUE TITLE
Half of slogan-phrase cut off on wide-screen

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#1]
![issue_1](https://user-images.githubusercontent.com/26530162/134050978-de9f9e44-765b-4905-b4cd-218200dbc9fc.jpg)

**Comment by IvanKuchin** [comment]
1. Make a reference to the commit that fixed the problem.
2. The problem still exists.

![image](https://user-images.githubusercontent.com/26530162/134577449-ff3dc14b-6d00-4dab-a02b-8e305fed1e70.png)

**Comment by IvanKuchin** [comment]
not fixed yet

**Comment by ghost** [comment]
- /resources/layout/css/theme.css : 658 (Need perform -  npm run prod)

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
