### ISSUE TITLE
User session kept for only 3 or 4 hours, even if user clicks checkbox "Remember me"

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#11]

**Comment by IvanKuchin** [comment]
1. Make a reference to the commit that fixed the problem.
2. The problem still exists.

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by IvanKuchin** [comment]
Chrome doesn't keep the session

**Comment by IvanKuchin** [comment]
FF is ok

**Comment by ghost** [comment]
User session kept for only 3 or 4 hours, even if user clicks checkbox "Remember me"
- /config/session.php : 34 
- /config/auth.php : 115

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by IvanKuchin** [comment]
closed due to inactivity
