### ISSUE TITLE
Edit .env and sql add

### ISSUE THREAD

**Issue by EmilFateev** [IvanKuchin/einsteiners.us#125]
Add to .env

FACEBOOK_ID= API_ID_KEY
FACEBOOK_SECRET= API_SECRET_KEY
FACEBOOK_REDIRECT=https://demo.einsteiners.su/auth/facebook/callback

GOOGLE_ID= API_ID_KEY
GOOGLE_SECRET= API_SECRET_KEY
GOOGLE_REDIRECT=https://demo.einsteiners.su/auth/goggle/callback

Add SQL to database

ALTER TABLE `users` ADD `facebook_id` VARCHAR(255) NULL AFTER `updated_at`;
ALTER TABLE `users` ADD `google_id` VARCHAR(255) NULL AFTER `updated_at`;

**Comment by IvanKuchin** [comment]
About SQL. 
Please open PR to [einsteners.us-db](https://github.com/IvanKuchin/einsteiners.us-db) repository

**Comment by IvanKuchin** [comment]
Closed by accident
