### ISSUE TITLE
Language mix

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#13]
![image](https://user-images.githubusercontent.com/26530162/134053374-b443e8da-e6d3-456d-887c-4454f5d29bf4.png)

**Comment by IvanKuchin** [comment]
1) Make a reference to the commit that fixed the problem. 
2) The problem still exists.

**Comment by ghost** [comment]
You need to update your browser cache

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.
The problem still exists.

**Comment by ghost** [comment]
- /resources/views/template/layout.blade.php : 511 / 519
