### ISSUE TITLE
Add Sql

### ISSUE THREAD

**Issue by EmilFateev** [IvanKuchin/einsteiners.us#143]
ALTER TABLE `calendars` ADD `date_time` VARCHAR(255) NULL AFTER `date_event`;
ALTER TABLE `events` ADD `date_time` VARCHAR(255) NULL AFTER `date_event`;

**Comment by EmilFateev** [comment]
ALTER TABLE `calendars` CHANGE `date_event` `date_event` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `events` CHANGE `date_event` `date_event` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `activities` CHANGE `date_event` `date_event` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `activities` ADD `date_time` VARCHAR(255) NULL AFTER `date_event`;

**Comment by IvanKuchin** [comment]
Создайте пож Pull Request в этот репозиторий https://github.com/IvanKuchin/einsteiners.us-db

PR должен содержать 2-а фаила 
1) xxxxxxx.up.sql - изменения 
2) xxxxxxx.down.sql - откат 

имя фаила должно быть в след формате 
XXXXYYZZ01_DESC.up.sql
XXXXYYZZ01_DESC.down.sql

XXXX - 2022
YY - месяц (03)
ZZ - день (11)

DESC - описание изменения 


Например: 
2022031101_add_event_date.up.sql
2022031101_add_event_date.down.sql

**Comment by IvanKuchin** [comment]
close it, please.
