### ISSUE TITLE
Remove all passwords from repo

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#16]
Example: https://github.com/einsteinersnet/einsteiners.net/blob/main/.env.example

**Comment by ghost** [comment]
This is a test file (the data is not correct)

**Comment by IvanKuchin** [comment]
Remove _ALL_ sensitive data from repository
It was just an example.

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by ghost** [comment]
Deleted

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by IvanKuchin** [comment]
no private data. confirmed
