### ISSUE TITLE
FireFox doesn't scale main page video to the screen size

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#18]
![image](https://user-images.githubusercontent.com/26530162/134080705-879f58c3-1516-4082-8789-c69083b2d9f5.png)

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by ghost** [comment]
You need to update your browser cache

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by ghost** [comment]
- /resources/layout/css/theme.css : 665

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
