### ISSUE TITLE
Numbers shifted beyond the area

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#19]
![image](https://user-images.githubusercontent.com/26530162/134081041-c84af229-c09c-4c6d-ba8f-f4bb729b4b7e.png)

**Comment by IvanKuchin** [comment]
1) Make a reference to the commit that fixed the problem. 
2) The problem still exists.

**Comment by ghost** [comment]
You need to update your browser cache

<img width="745" alt="image" src="https://user-images.githubusercontent.com/90713725/134690417-bbc5ea91-4a49-4d11-9910-74a9aa35be26.png">

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by ghost** [comment]
- /resources/layout/css/theme.css : 910

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
