### ISSUE TITLE
Hamburger flickering on wide-screen

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#2]
![image](https://user-images.githubusercontent.com/26530162/134051140-af3f53eb-fe81-4af3-9327-ba180aa72f27.png)

**Comment by ghost** [comment]
Укажите Ваше разрешение экрана и браузер какой использовался

<img width="933" alt="image" src="https://user-images.githubusercontent.com/90713725/134571537-a2a71d49-143a-41d8-bd86-38fa778b2dd2.png">

<img width="889" alt="image" src="https://user-images.githubusercontent.com/90713725/134571579-036c113e-6b6e-4a4e-9b3d-3dcc76741629.png">

**Comment by IvanKuchin** [comment]
https://user-images.githubusercontent.com/26530162/134576643-4bf3c0c6-9075-4a8a-9a8a-03a708d48d10.MOV

**Comment by IvanKuchin** [comment]
not fixed yet

**Comment by ghost** [comment]
- /resources/views/template/layout.blade.php : 510

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
