### ISSUE TITLE
Typo in company name

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#20]
![image](https://user-images.githubusercontent.com/26530162/134081121-6320a7cf-eeca-4535-a45d-5836b297c1bb.png)

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by ghost** [comment]
You need to update your browser cache

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/90713725/134690298-852292c4-9bf9-46d8-a9aa-40c5d99f64c9.png">

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by ghost** [comment]
Edit - /resources/lang/en.json(ru.json)

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
