### ISSUE TITLE
Idling logged in user w/o "remember me" must be logged out after 1 hour

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#25]
Current setting 2 hours
![image](https://user-images.githubusercontent.com/26530162/134707735-da3d89ad-96fc-4c46-b162-8ce3ec74ae0c.png)

**Comment by IvanKuchin** [comment]
assign PR to this issue before closing

**Comment by ghost** [comment]
- /config/session.php : 34 
- /config/auth.php : 115
