### ISSUE TITLE
Calendar is invisible in FF

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#26]
![image](https://user-images.githubusercontent.com/26530162/134708756-2a389948-5332-4d14-bfda-6ff21caec0bb.png)

**Comment by ghost** [comment]
- /resources/views/livewire/activitie/activitie.blade.php : 177,378
 - /resources/views/livewire/event/event.blade.php : 128,241
  - /resources/views/livewire/calendar/list.blade.php : 139,277
  
  (Сhanged to input mask)

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by nmarkelova** [comment]
i could enter any numbers and the system allows to do it. Still no calendar.
Time of the event from be separate: Event start time , event end time
