### ISSUE TITLE
Using "tomorrow" word as a date in FF throws exception

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#28]
![image](https://user-images.githubusercontent.com/26530162/134709732-171f10f8-195b-476c-b61a-0c1a1761b651.png)

**Comment by ghost** [comment]
Calendar is invisible in FF
- /resources/views/livewire/activitie/activitie.blade.php : 177,378 
- /resources/views/livewire/event/event.blade.php : 128,241 
- /resources/views/livewire/calendar/list.blade.php : 139,277

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
