### ISSUE TITLE
Event search searching for events that are in wrong locations

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#29]
![image](https://user-images.githubusercontent.com/26530162/134710940-51897c90-da1f-48e8-bbc8-4e740fee4ee9.png)

![image](https://user-images.githubusercontent.com/26530162/134711088-67a66d53-182b-4535-8ced-5c5e7d93398b.png)

**Comment by ghost** [comment]
- /resources/views/livewire/search.blade.php : 14-63
- /app/Http/Livewire/Search.php : 51-62

22. Search (Delete City and Search Autor)

**Comment by nmarkelova** [comment]
where is the search by location?

**Comment by IvanKuchin** [comment]
Not relevant anymore
