### ISSUE TITLE
Default language must be EN

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#3]

**Comment by IvanKuchin** [comment]
not fixed yet

**Comment by ghost** [comment]
Default language must be EN 
- /config/app.php : 83,96,109
 - /app/http/Middleware/LocaleDetect.php : 23-29
  - /resources/views/template/layout.blade.php : 337-342
   - /resources/views/includes/menu.blade.php : 3-8
