### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by nmarkelova** [IvanKuchin/einsteiners.us#31]
Copy all past and future events from Facebook to Web
Example of the event - https://www.facebook.com/events/2966399216966473?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22page%22%7D]%7D

**Comment by nmarkelova** [comment]
copy from Facebook events https://www.facebook.com/Einsteiners.events/photos/?ref=page_internal

**Comment by IvanKuchin** [comment]
Наполнение сайта не относится к разработке
