### ISSUE TITLE
Screen size

### ISSUE THREAD

**Issue by nmarkelova** [IvanKuchin/einsteiners.us#32]
I have a small laptop and can't click on the menu - need to make the screen bigger in order to be able.

**Comment by ghost** [comment]
Done

**Comment by nmarkelova** [comment]
https://user-images.githubusercontent.com/24485888/151679733-3878faa2-9dd8-4441-9eb7-4b5ff760ff29.MOV

**Comment by IvanKuchin** [comment]
Мобильная или десктоп версия сайта генерируется на сервере, поэтому переключение между версиями сайта требует запрос на сервер.
