### ISSUE TITLE
Сontact

### ISSUE THREAD

**Issue by nmarkelova** [IvanKuchin/einsteiners.us#38]
When you click on the menu Сontact - it opens and its called Сontacts.
Should be Сontact without "S"

**Comment by ghost** [comment]
Done

**Comment by nmarkelova** [comment]
1. email should be info@einsteiners.us
2. map should be in English
<img width="1139" alt="Screen Shot 2022-01-29 at 7 25 12 PM" src="https://user-images.githubusercontent.com/24485888/151682123-ab6dc4e4-8ac9-441c-b9b1-8ed7b938086b.png">
