### ISSUE TITLE
Phone typing issue on registration page

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#4]
Hello, 

    On registration page, click on phone field and type single number. This very first number doesn't appear in the phone number.

**Comment by ghost** [comment]
The first character is registered under the input mask character (Input should start with the second character?)

**Comment by IvanKuchin** [comment]
1) here I click on the phone field
![image](https://user-images.githubusercontent.com/26530162/134575244-e094a453-d1eb-4b81-93f7-d9cb9f5e8b99.png)

2) Type "5"
![image](https://user-images.githubusercontent.com/26530162/134575335-078510a6-e320-4d8f-b2c7-37985d8e5c6a.png)

**Comment by ghost** [comment]
Change the language to EN, for RU, the first and second digits are +7 (9 is the standard

**Comment by IvanKuchin** [comment]
Language is not important
Number that I typed must appear. First number typed in Phone field is lost.

**Comment by IvanKuchin** [comment]
not fixed yet

**Comment by ghost** [comment]
Phone typing issue on registration page 
- /resources/layout/js/action.min.js: 51 (Edit Function Mask)

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
