### ISSUE TITLE
Add download document form 

### ISSUE THREAD

**Issue by ghost** [IvanKuchin/einsteiners.us#42]

**Comment by nmarkelova** [comment]
[COVID-19 Health Screening Form1.docx](https://github.com/einsteinersnet/einsteiners.net/files/7373571/COVID-19.Health.Screening.Form1.docx
[COVID-19 Liability Waiver1.docx](https://github.com/einsteinersnet/einsteiners.net/files/7373572/COVID-19.Liability.Waiver1.docx)
[Photo Release1.docx](https://github.com/einsteinersnet/einsteiners.net/files/7373573/Photo.Release1.docx)
[Waiver and Release of Liability1.docx](https://github.com/einsteinersnet/einsteiners.net/files/7373575/Waiver.and.Release.of.Liability1.docx)
)
