### ISSUE TITLE
Incorrect "consent to the processing of personal data"

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#6]
![image](https://user-images.githubusercontent.com/26530162/134051876-c525de9a-24d3-4129-a344-096e6130e6fa.png)

**Comment by ghost** [comment]
Необходимо прислать точный текст для данных соглашений

**Comment by ghost** [comment]
Need content

**Comment by nmarkelova** [comment]
You will be required to provide us with Personal Information if you choose to engage with certain functions on our Mobile Application or Website or with us in-store. This includes when you:
* Create an Einsteiners account. To create an Einsteiners account, you will provide us with personal identifiers, such as your name, date of birth, and email address. Once your account is created, we will maintain your Einsteiners username and password.
* Make a purchase. If you make a purchase, you will need to provide your personal identifiers, such as your name, physical address, and email address, as well as customer, records information, including payment card number. When you make a purchase, we also collect and maintain commercial information about you, such as products purchased, obtained, or considered, and purchasing and consuming tendencies.
* Participate in social media. You may choose to share your own personal identifiers, such as your name and any other personal information you choose to include in your post, through our ratings and review pages, and social media pages. If you tag a publicly available social media post with a reference to Einsteiners, with your permission, we may also collect an image of you that you choose to include in your post.
* Interact with us. When you communicate with us or send us any feedback, questions, requests for support, comments, suggestions, ideas, or interact with us in any way, you will need to provide personal identifiers, including your name and email address.
* Subscribe to Einsteiners updates and promotions. You have the option of signing up for Einsteiners email updates or our FUN text message updates for products, services and offers that may be of interest to you. To sign-up, you will need to provide us with personal identifiers such as your name, email address, and/or telephone number. When you sign-up, we may use your personal information to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.
* Move around in our store. If you visit Einsteiners locations, video of you will be captured by our CCTV footage.
