### ISSUE TITLE
.env -> config/config.txt

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#61]
Make .env as a soft link to config/config.txt
And make sure that changes in config.txt taken into consideration without site re-building.

**Comment by ghost** [comment]
Edit DockerFile - RUN mkdir config_env && cp .env.example config_env/.env && ln -s config_env/.env

**Comment by IvanKuchin** [comment]
Issue fixed - ok

Need to assign pull request !!!

![image](https://user-images.githubusercontent.com/26530162/151644100-d913502c-211c-4ce2-bf3f-6c1d318dda83.png)
