### ISSUE TITLE
Dialogs windows overlap

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#7]
Reproduce steps:

1. Logout , if you are logged-in
2. look for event "Event"
3. click  "Signup"
4. click "privacy policy and user agreement website."

User Agreement is not visible

**Comment by ghost** [comment]
Форма авторизации, регистрации не является модульном окном (Это отдельные страницы), или я не правильно понял ошибку?

**Comment by IvanKuchin** [comment]
Извините за слово "модульное". Я убрал его из обращения.
Шаги для воспроизведения проблемы 
1) click "Calendar"
![image](https://user-images.githubusercontent.com/26530162/134573903-afd07bc7-d170-40b7-b23c-49936fa52bca.png)
2) Click "Sign-up"
![image](https://user-images.githubusercontent.com/26530162/134574227-e7a9fad9-edb0-4ca8-b1b1-e7ab36e50a45.png)
3) Click "user agreement"
![image](https://user-images.githubusercontent.com/26530162/134574453-84ea7d26-f810-4482-8700-3b0d6e4b2ad5.png)
4) Close both: user agreement, and sign-up
![image](https://user-images.githubusercontent.com/26530162/134574579-7c321fe8-eb7d-4f08-a876-76bca92d78bd.png)
![image](https://user-images.githubusercontent.com/26530162/134574638-f9190972-d7be-4bf5-83a2-8712fd195a43.png)

5) Click again "Sign up" 
![image](https://user-images.githubusercontent.com/26530162/134574698-cb7f5f2a-e1f6-4181-b98f-23b4cf8a58a9.png)

6) No images
![image](https://user-images.githubusercontent.com/26530162/134574756-53bb487d-ea5a-4f91-a1f6-75cb3f244fa8.png)

**Comment by ghost** [comment]
- /resources/layout/css/theme.css : 2485 (npm run prod)

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by IvanKuchin** [comment]
При закрытии формы бронирования "слетает" выбранный день.

**Comment by IvanKuchin** [comment]
closed due to inactivity
