### ISSUE TITLE
Event image is invisible

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#8]
Reproduce steps:

1. Logout , if you are logged-in
2. look for event "Event"
3. click "Signup"

Event image is invisible

![image](https://user-images.githubusercontent.com/26530162/134052512-9a325975-ad9a-42b8-8dcf-b543db5434de.png)

**Comment by ghost** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/90713725/134568838-54923075-c2e4-4a69-bc27-35a15db1f6d6.png">

**Comment by IvanKuchin** [comment]
Make a reference to commit that fixed the problem.

**Comment by IvanKuchin** [comment]
1) The problem still exists. See first 4 steps here https://github.com/einsteinersnet/einsteiners.net/issues/7
2) Make a reference to commit that fixes the issue

**Comment by ghost** [comment]
You need to update your browser cache

**Comment by IvanKuchin** [comment]
1. The problem still exists
2. Make a reference to commit that fixes the issue

**Comment by ghost** [comment]
- /resources/views/livewire/calendar/list.blade.php (add wire:ignore) : 362, : 396

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by IvanKuchin** [comment]
Reproduce steps are not relevant
----
look for event "Event"
click "Signup"
----
