### ISSUE TITLE
Cookie consent continues to re-appear even if user "agreed"

### ISSUE THREAD

**Issue by IvanKuchin** [IvanKuchin/einsteiners.us#9]
![image](https://user-images.githubusercontent.com/26530162/134052774-652c78f4-8cec-42dd-abeb-efac64a0699d.png)

**Comment by IvanKuchin** [comment]
Make a reference to the commit that fixed the problem.

**Comment by ghost** [comment]
Cookie consent continues to re-appear - position 
- /resources/layout/css/theme.css : 2472

**Comment by IvanKuchin** [comment]
Please use standard GitHub tools 
Here is the description "how to": https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
